#!/usr/bin/env python

import json
from requests.auth import HTTPBasicAuth
from urllib2 import urlopen, Request
import os
import requests
import time
from kafka import SimpleProducer, KafkaClient
import gzip
import os

start = time.time()
kafka = KafkaClient('ec2-52-8-111-39.us-west-1.compute.amazonaws.com:9092')
producer = SimpleProducer(kafka)

github_user_alvin = "alvin"
github_pass_alvin = os.environ['alvin_pass']

github_user_vimal1 = "vimal1"
github_pass_vimal1 = os.environ['vimal1_pass']

following_url = "https://api.github.com/users/"
per_page="&per_page=100"

i=0
def get_following(url_tail, user, following, page):
  global i
  global github_user_vimal1
  global github_user_alvin
  global github_pass_vimal1
  global github_pass_alvin
  if i < 4999:
    json_response = []
    github_user = github_user_vimal1
    github_pass = github_pass_vimal1
    try:
      request = Request(following_url + user + "/following" + url_tail + per_page)
      request.add_header('Authorization', 'token %s' % github_pass)
      response = urlopen(request, timeout=5)
      json_response = json.loads(response.read())
    except requests.exceptions.Timeout as e:
      time.sleep(30)
      return following
    except requests.exceptions.ConnectionError as e:
      time.sleep(30)
      return following
    except requests.exceptions.HTTPError as e:
      time.sleep(30)
      return following
    except Exception, e:
      print e
      return following
    i+=1
  else:
    json_response = []
    github_user = github_user_alvin
    github_pass = github_pass_alvin
    try:
      request = Request(following_url + user + "/following" + url_tail + per_page)
      request.add_header('Authorization', 'token %s' % github_pass)
      response = urlopen(request, timeout=5)
      json_response = json.loads(response.read())
    except requests.exceptions.Timeout as e:
      time.sleep(30)
      return following
    except requests.exceptions.ConnectionError as e:
      time.sleep(30)
      return following
    except requests.exceptions.HTTPError as e:
      time.sleep(30)
      return following
    except Exception, e:
      print e
      return following
    i+=1
    if i==9998:
     i = 0
  if json_response == [] or page==10:
    return following
  else:
    following += json_response
    page +=1
    get_following("?page="+str(page), user, following, page)
    return following

flag = 0
count = 0
with open("following-insight.json","w") as op_file:
  for fellow in insight_fellows:
    user = fellow
    print "\ncount: ", count
    following = []
    following_dict = {}
    following = get_following("?page=1", user, [], 1)
    following_dict["login"] = user
    following_dict["following"] = following
    print following_dict
    count += 1
    op_file.write(json.dumps(following_dict)+"\n")
    producer.send_messages("scrap-following-insight", json.dumps(following_dict))
    print "total people followed: ", len(following)
    #except Exception, e:
     # print e

stop = time.time()
print stop-start


