#!/usr/bin/env python

import json
from requests.auth import HTTPBasicAuth
import os
import requests
import time
from kafka import SimpleProducer, KafkaClient

start = time.time()
kafka = KafkaClient('localhost:9092')
producer = SimpleProducer(kafka)

github_user_insight2 = os.environ['github_insight2']
github_pass_insight2 = os.environ['github_insight2_pass']

github_user_insight3 = os.environ['github_insight3']
github_pass_insight3 = os.environ['github_insight3_pass']

following_url = "https://api.github.com/users/"

files = os.listdir("../../data/users_data")
filenums = [x[5:] for x in files]
filenumsints = [int(x) for x in filenums]
filenumsdesired = [x for x in filenumsints if x < 150000]
filesdesired = ["users"+str(x) for x in filenumsdesired]

per_page="&per_page=100"

i = 0

def get_following(url_tail, user, following, page):
  global i
  global github_user_insight2
  global github_user_insight3
  global github_pass_insight2
  global github_pass_insight3
  if i < 4999:
    github_user = github_user_insight2
    github_pass = github_pass_insight2
    i+=1
  else:
    github_user = github_user_insight3
    github_pass = github_pass_insight3
    i+=1
    if i==9998:
      i = 0
#  print "i: ", i
  response = requests.get(following_url + user + "/following" + url_tail + per_page, auth=HTTPBasicAuth(github_user, github_pass))
  json_response = json.loads(response.text)
  if json_response == []:
    return following
  else:
    following += json_response
    page +=1
    get_following("?page="+str(page), user, following, page)
    return following

count = 0

for filename in filesdesired:
  ip = open("../../data/users_data/"+filename, "rb")
  json_records = json.load(ip)
  usernames = [(x['login'], x['id']) for x in json_records]
  for users in usernames:
    user = users[0]
    user_id = users[1]
    following = []
    following_dict = {}
    following = get_following("?page=1", user, [], 1)
    following_dict["login"] = user
    following_dict["id"] = user_id
    following_dict["following"] = following
    count += 1
    producer.send_messages("users-following-good-2", json.dumps(following_dict))
    print "\ncount: ", count, " for user: ", user
    print "total people followed: ", len(following)

stop = time.time()
print stop-start

