#!/usr/bin/env python

from cassandra.cluster import Cluster
from cqlengine import columns
from cqlengine.models import Model
from cqlengine import connection
from cqlengine.management import sync_table
import operator

connection.setup(['52.8.127.252', '52.8.41.216'], "watch_events")
cluster = Cluster(['52.8.127.252', '52.8.41.216'])
session = cluster.connect('watch_events')

class top10weeklyrepos(Model):
  reponame = columns.Text(primary_key=True)
  watchcount = columns.Integer()
  def __repr__(self):
    return (self.reponame, self.watchcount)

cql = "SELECT * FROM weeklytrends";
stmt = session.execute(cql)
response = []
for repo in stmt:
  response.append(repo)
jsonresponse = [(x.reponame,  x.watchcount) for x in response]
jsonresponse.sort(key=operator.itemgetter(1), reverse=True)

sync_table(top10weeklyrepos)
top10 = jsonresponse[0:10]
print top10

for val in top10:
    top10weeklyrepos.create(reponame = val[0], watchcount = val[1])

