#!/usr/bin/env python

import json
from pprint import pprint
from kafka import SimpleProducer, KafkaClient

# To send messages synchronously
kafka = KafkaClient("localhost:9092")
producer = SimpleProducer(kafka)

# Note that the application is responsible for encoding messages to type str

def sentences(file_name):
    with open(file_name) as f:
        for line in f:
            data = json.loads(line)
            producer.send_messages("2015-01-01-0", data)

             
ip_file = "../gitarchive/2015-01-01-0.json"

sentences(ip_file)
