#!/usr/bin/env python

from requests.auth import HTTPBasicAuth
import requests
import json
import time
import os
github_user_insight = os.environ['github_insight1']
github_pass_insight = os.environ['github_insight1_pass']

github_user_personal = os.environ['github_user']
github_pass_personal = os.environ['github_pass']

#requests.get('https://api.github.com/user', auth=HTTPBasicAuth(github_user, github_pass))

start = time.time()
index = 12961006
per_page = "&per_page=100"

def call_github(index, github_user, github_pass, j):
  url = "https://api.github.com/users?since="+str(index)+per_page
  response = requests.get(url, auth=HTTPBasicAuth(github_user, github_pass))
  jsondata = json.loads(response.text)
  print type(jsondata)
  next_index = jsondata[-1]["id"]
  op_file = "../data/users_data/users" + str(index)
  with open(op_file, 'w') as outputfile:
    json.dump(jsondata, outputfile)
  print next_index, j
  return next_index

i = 0
while True:
  if i<4999:
    index = call_github(index, github_user_insight, github_pass_insight, i) 
    i+=1
  else:
    index = call_github(index, github_user_personal, github_pass_personal, i)
    i+=1
    if i==9998:
      i=0

  
stop = time.time()
print stop-start
